import { jest } from '@jest/globals';

const createMockModel = () => ({
  findUnique: jest.fn(() => Promise.resolve(null)),
  findFirst: jest.fn(() => Promise.resolve(null)),
  findMany: jest.fn(() => Promise.resolve([])),
  create: jest.fn((args: any) => Promise.resolve({ id: 'mock-id', ...args?.data })),
  createMany: jest.fn(() => Promise.resolve({ count: 0 })),
  update: jest.fn((args: any) => Promise.resolve({ id: 'mock-id', ...args?.data })),
  updateMany: jest.fn(() => Promise.resolve({ count: 0 })),
  upsert: jest.fn((args: any) => Promise.resolve({ id: 'mock-id', ...args?.create })),
  delete: jest.fn(() => Promise.resolve({ id: 'mock-id' })),
  deleteMany: jest.fn(() => Promise.resolve({ count: 0 })),
  count: jest.fn(() => Promise.resolve(0)),
});

export const prisma = {
  user: createMockModel(),
  relationship: createMockModel(),
  relationshipMember: createMockModel(),
  session: createMockModel(),
  innerWorkSession: createMockModel(),
  innerWorkMessage: createMockModel(),
  stageProgress: createMockModel(),
  userVessel: createMockModel(),
  userEvent: createMockModel(),
  emotionalReading: createMockModel(),
  identifiedNeed: createMockModel(),
  boundary: createMockModel(),
  userDocument: createMockModel(),
  sharedVessel: createMockModel(),
  consentedContent: createMockModel(),
  commonGround: createMockModel(),
  agreement: createMockModel(),
  consentRecord: createMockModel(),
  message: createMockModel(),
  preSessionMessage: createMockModel(),
  empathyDraft: createMockModel(),
  empathyAttempt: createMockModel(),
  empathyValidation: createMockModel(),
  reconcilerResult: createMockModel(),
  reconcilerShareOffer: createMockModel(),
  strategyProposal: createMockModel(),
  strategyRanking: createMockModel(),
  emotionalExerciseCompletion: createMockModel(),
  globalLibraryItem: createMockModel(),
  invitation: createMockModel(),
  notification: createMockModel(),
  userMemory: createMockModel(),
  need: createMockModel(),
  needScore: createMockModel(),
  needsAssessmentState: createMockModel(),
  person: createMockModel(),
  personMention: createMockModel(),
  gratitudeEntry: createMockModel(),
  gratitudePreferences: createMockModel(),
  meditationSession: createMockModel(),
  meditationStats: createMockModel(),
  meditationFavorite: createMockModel(),
  meditationPreferences: createMockModel(),
  auditLog: createMockModel(),
  $executeRaw: jest.fn(() => Promise.resolve(0)),
  $queryRaw: jest.fn(() => Promise.resolve([])),
  $transaction: jest.fn((p: any) => Promise.all(Array.isArray(p) ? p : [])),
};

export default prisma;
